### ISSUE TITLE
CLIENT- components

### ISSUE THREAD

**Issue by Lovertab** [SuperRonanCraft/bootcamp-Tomodachi#11]
Login 
- [x] #48
- [x] define login form 
- [x] useState for email and password 
- [x] use mutation for login user
- [x] define a handle input change event
- [x] define a handle form submit event
- [x] return a form with username and password
- [x] export component

----------------------------------------------
Sign up
- [x] import auth, use mutation from apollo, and add _user from mutations
- [x] define sign up form 
- [x] useState for username, email, and password
- [x] use mutation for adding user
- [x] define a handle input change event
- [x] define a handle form submit event
- [x] component returns a form with the ability to input a username, email, and password
- [x] export component
----------------------------------------------
Nav Bar
- [x] import signup form, login form, and auth
Login State
- [x] show logout button 
- [x] show profile button
Guest State
- [x] show login button
Neutral State
- [x] leaderboard button

**Comment by SuperRonanCraft** [comment]
awesome work!
