### ISSUE TITLE
CLIENT-pages

### ISSUE THREAD

**Issue by Lovertab** [SuperRonanCraft/bootcamp-Tomodachi#12]
Profile page
- [x] #102
- [x] display saved game data
- [x] display button to delete game data
- [x] create game button 
----------------------------------------------------------
Game page
- [x] display game
- [x] health bar, hunger, age, happiness (optional- cleanliness) 
----------------------------------------------------------
Leaderboard page
- [x] #107

----------------------------------------------------------
Home page
Login state
- [x] create game button

**Comment by Xydra01** [comment]
Still has a lot of stuff that needs to be done didn't mean to close this.
